baseurl = "https://example.org/"
languageCode = "en-us"
title = "Gelmis Bartulis"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]


	name = "Gelmis Bartulis"
	description = "Software developer"

	# The path must be relative to the static folder
	favicon = "favicon.png"


	# Navigation
	[params.navigation]
		brand = "Welcome"

		[params.navigation.links]
			about     = "About"
			services  = "Work"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'back2.jpg' at './static/img' with your own.
		slogan     = "Hi, I'm Gelmis."
		subtitle   = "a"
		buttonText = "More"

    [params.social]
        GitHub = "gelmisb"
        LinkedIn = "gelmisb"
        Instagram = "thegsb"
        Email   = "gelmis.bartulis@gmail.com"
        Facebook = "gbartulis"

	# About section
	[params.about]
		headline    = "We"
		description = "[Lorem]"
		buttonText  = "Details"



	# Service section
	[params.services]
		headline = "Character"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Fine work"
            description = "Projects are refined to the point that the client is too happy."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Quick and punctual"
			description = "Efficient project development."

		[[params.services.list]]
            icon = "fab fa-angellist"
            title = "Friendly"
            description = "Easy to work with."

        [[params.services.list]]
            icon = "fas fa-briefcase"
            title = "Adaptable"
            description = "Quick to adapting to new environments"

        headline2 = "I work in different environments"

        [[params.services.list2]]
            icon = "fal fa-at"
            title = "Junior Web Developer"
            description = "AngularJS, AngularJS2, JS, Ember.JS, jQuery, PHP, IBM Watson integration"

        [[params.services.list2]]
			icon = "fab fa-android"
			title = "Android Full-stack Developer"
			description = "Java, Kotlin, IBM Watson integration"

		[[params.services.list2]]
            icon = "ab fa-connectdevelop"
            title = "Software Developer"
            description = "PHP, Python, Java, C#"

		[[params.services.list2]]
            icon = "far fa-gamepad"
            title = "Game Developer"
            description = "Java, C#"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"



	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Let me know if you would like to work on any project or would like to get in touch!"
		phone = "+353 89 493 9050 "
		email = "gelmis.bartulis@gmail.com"

		[params.aside.button]
			text = "Go up"
			link = "#hero"

